# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# Line length - disabled for documentation
MD013: false

# Inline HTML - allowed for advanced formatting
MD033: false

# First line should be top-level heading - frontmatter is fine
MD041: false

# Multiple headings with same content - allowed for tables
MD024:
  siblings_only: true

# Trailing punctuation in heading - allow ? and :
MD026:
  punctuation: '.,;!'

# Ordered list item prefix - allow any number
MD029:
  style: 'ordered'

# Fenced code blocks should have a language specified
MD040: true

# Link fragments should be valid
MD051: true

# Reference links and images should use a label that is defined
MD052: true
